version: "3.8"
services:
  database:
    container_name: my-database-container
    image: mysql:8.0.35
    # command: --default-authentication-plugin=mysql_native_password
    # command: --authentication_policy=caching_sha2_password
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DOCKER_DB_PORT:$DB_PORT
    volumes:
      - db_volume:/var/lib/mysql
  nest:
    depends_on:
      - database
    container_name: my-server-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $DOCKER_PORT:$PORT
    environment:
      - DB_HOST=database
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - ENV=$ENV
      - PORT=$PORT
      - APP_NAME=$APP_NAME
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRE_DURATION=$JWT_EXPIRE_DURATION
      - ALLOWED_FILE_SIZE=$ALLOWED_FILE_SIZE

volumes:
  db_volume:
